### ISSUE TITLE
dose gozim support the zim file locate on the samba filesystem?

### ISSUE THREAD

**Issue by wliment** [akhenakh/gozim#28]
run gozim on raspberrypi.
 I try mount a samba share directroy  on the  local directory
but when i try run the gozimindex command  trigger a error

`./gozimindex -path=wikipedia_zu_all_nopic_2016-05.zim -index=tttt.index
[custom] [en cjk standard simple keyword]
panic: IO error: tttt.index/store: Invalid argument

goroutine 1 [running]:
main.main()
	/home/akh/dev/go/src/github.com/akhenakh/gozim/cmd/gozimindex/main.go:79 +0x51c

goroutine 5 [chan receive]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0x1074ce00)
	/home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:40 +0x58
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
	/home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x80

goroutine 6 [chan receive]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0x1074ce00)
	/home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:40 +0x58
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
	/home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x80

goroutine 7 [chan receive]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0x1074ce00)
	/home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:40 +0x58
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
	/home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x80

goroutine 8 [chan receive]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0x1074ce00)
	/home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:40 +0x58
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
	/home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x80

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_arm.s:1322 +0x4`

**Comment by akhenakh** [comment]
I assume it's caused by the Bleve index probably trying to mmap() a file over SMBFS/CIFS try tweaking your mount

**Comment by wliment** [comment]
@akhenakh  
i enable option  **_use mmap = yes_**   in smb server  conf file.
 but the error remain
