### ISSUE TITLE
"unsupported version, 5 only" error

### ISSUE THREAD

**Issue by hffqyd** [akhenakh/gozim#38]
Hi, thanks for your great gozim.

When I was using `gozimindex` to index a zim file with the code below:

```bash
gozimindex -path=wikipedia_en_all_nopic_2019-10.zim -index=wiki_en_nopic_201
9-10.idx
```
there was an error.

```bash
panic: unsupported version, 5 only

goroutine 1 [running]:
main.main()
        /home/akh/dev/go/src/github.com/akhenakh/gozim/cmd/gozimindex/main.go:49 +0x11b

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/lib/go/src/runtime/proc.go:90
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/lib/go/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/lib/go/src/runtime/malloc.go:712
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc208032060)
        /home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:37
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
        /home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x66

goroutine 6 [runnable]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc208032060)
        /home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:37
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
        /home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x66

goroutine 7 [runnable]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc208032060)
        /home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:37
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
        /home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x66

goroutine 8 [runnable]:
github.com/blevesearch/bleve/index/upside_down.AnalysisWorker(0xc208032060)
        /home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:37
created by github.com/blevesearch/bleve/index/upside_down.NewAnalysisQueue
        /home/akh/dev/go/src/github.com/blevesearch/bleve/index/upside_down/analysis_pool.go:32 +0x66
```

Could you please tell me what's the matter?

Thanks.

**Comment by burkemw3** [comment]
Looks like major version 6 of ZIM files was created around 2018-Mar ([src](https://wiki.openzim.org/w/index.php?title=ZIM_file_format&diff=prev&oldid=2897)) that added support for at least 'extended clusters'. ZIM File docs say "Major version is updated when an incompatible change is integrated in the format (a lib made for a version N will probably not be able to read a version N+1)".

Long term fix is to add support for extended clusters.

Docs also say "version 6 (the same that version 5 + potential extended cluster)". In the short term, it might be possible to allow version 6, and fail only if an actual extended cluster is found

**Comment by burkemw3** [comment]
Referenced commit has barely tested support for v6 zim files.

**Comment by Aws505** [comment]
I have tested burkemw3/gozim with wikipedia_en_all_nopic_2020-05.zim  and unfortunately it does not work. The modifications in article.go seem to derp gozim's ability to look up articles: gozimhttpd fails, then, to look up articles in zims of v5+ and v5-

If I figure out how to get more info (or a solution), I'll post it here.

**Comment by gaetanlhf** [comment]
This issue has been fixed by the PR https://github.com/akhenakh/gozim/pull/41, made by @benthor.
So maybe it's time to close it?
